### ISSUE TITLE
Empty Build.

### ISSUE THREAD

**Issue by exislow** [mvsde/svelte-micro-frontend#11]
This is a great idea and exactly what I am looking for. Thank you for your effort. But is this still working with scvelte? 

I have issues to get working with my Svelte project: https://github.com/exislow/freeDSP-Aurora-Svelte-Frontend/tree/micro

Every time I try to build my project, this happens:

```
$ npm run build

> sveltekit-bulma-8chan@0.0.1 build
> vite build

9:48:00 PM [vite-plugin-svelte] you are building for production but compilerOptions.dev is true, forcing it to false
vite v4.4.11 building for production...
✓ 3 modules transformed.
dist/src/app.html                   0.35 kB │ gzip: 0.25 kB
dist/svelte-micro-frontend.iife.js  0.09 kB │ gzip: 0.11 kB │ map: 0.11 kB
✓ built in 42ms

Process finished with exit code 0
```

But `dist/svelte-micro-frontend.iife.js` only contains this code:

```
(function(){"use strict"})();
//# sourceMappingURL=svelte-micro-frontend.iife.js.map
```

Do you have any idea whats wrong?

**Comment by mvsde** [comment]
I haven’t worked with Vite in quite some time, so there may be some changes in how Rollup is used and how the build options are passed to Rollup.

I’ll look into the Vite/Rollup configuration and check whether this still works with or can be ported to newer Vite and Svelte versions.

**Comment by exislow** [comment]
This is very kind of you, thank you very much! I am kinda stuck here :-/

**Comment by mvsde** [comment]
I updated this repository to the latest versions of Svelte and Vite and at least in this repository everything still works as expected.

It looks like you’re using SvelteKit and that is probably not compatible with the micro frontend approach from this repository.

The SPA build provided by SvelteKit is probably the closest you can get to a micro frontend: https://kit.svelte.dev/docs/single-page-apps.

**Comment by exislow** [comment]
Thank you for your effort. My app is already set to SPA mode but there are still plenty of files, which are generated. I will try to re-write my app using Svelte instead of SvelteKit. This will be a pain in the ass...
